language: cpp

addons:
  homebrew:
    packages:
      - cmake
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      #OpenGL related dependencies
      - libglfw3-dev
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev
      #Compiler
      - gcc-8
      - g++-8
      - gcc-9
      - g++-9

jobs:
  include:
    - dist: bionic
      compiler: gcc
      env:
        - BUILD_NAME="BIONIC_GCC-8"
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - dist: focal
      compiler: gcc
      env:
        - BUILD_NAME="FOCAL_GCC-8"
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - dist: bionic
      compiler: gcc
      env:
        - BUILD_NAME="BIONIC_GCC-9"
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

    - dist: focal
      compiler: gcc
      env:
        - BUILD_NAME="FOCAL_GCC-9"
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

    - os: osx
      osx_image: xcode12
      compiler: clang
      env:
        - BUILD_NAME="OSX_CLANG"


before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cmake --no-warn-unused-cli -HEditor -Bbuild -G"Unix Makefiles"
  - cmake --build build
